export const CATEGORY_LABELS_AR: Record<string, string> = {
  real_estate: 'عقارات',
  cars: 'سيارات',
  cars_rent: 'تأجير سيارات',
  'spare-parts': 'قطع غيار السيارات',
  stores: 'المتاجر والمولات',
  restaurants: 'مطاعم',
  groceries: 'محلات غذائيه',
  'food-products': 'منتجات غذائية',
  electronics: 'إلكترونيات',
  'home-tools': 'أدوات منزلية',
  furniture: 'اثاث ومفروشات',
  doctors: 'أطباء',
  health: 'الصحة',
  teachers: 'معلمون',
  education: 'تعليم',
  jobs: 'وظائف',
  shipping: 'الشحن والتوصيل',
  'mens-clothes': 'الملابس الرجاليه والاحذيه',
  'watches-jewelry': 'ساعات ومجوهرات',
  'free-professions': 'المهن الحره والخدمات',
  'kids-toys': 'مستلزمات ولعب الاطفال',
  gym: 'جيمات',
  construction: 'مواد البناء والتشطيبات',
  maintenance: 'الصيانه العامه',
  'car-services': 'خدمات وصيانه السيارات',
  'home-services': 'خدمات وصيانه المنازل',
  'lighting-decor': 'إضاءة وديكور',
  animals: 'طيور وحيوانات',
  'farm-products': 'منتجات مزارع ومصانع',
  wholesale: 'بيع الجمله',
  'production-lines': 'مواد وخطوط الانتاج',
  'light-vehicles': ' دراجات و مركبات خفيفة',
  'heavy-transport': 'نقل ومعدات ثقيله',
  tools: 'عددو مستلزمات',
  'home-appliances': 'أجهزة منزلية',
  missing: 'مفقودين',
};

export const ALL_CATEGORIES = Object.values(CATEGORY_LABELS_AR);
export const ALL_CATEGORIES_OPTIONS = Object.entries(CATEGORY_LABELS_AR).map(([slug, label]) => ({ value: slug, label }));
