export const CATEGORY_LABELS_AR: Record<string, string> = {
  real_estate: 'عقارات',
  cars: 'سيارات',
  cars_rent: 'تأجير سيارات',
  'spare-parts': 'قطع غيار',
  stores: 'محلات',
  restaurants: 'مطاعم',
  groceries: 'بقالة',
  'food-products': 'منتجات غذائية',
  electronics: 'إلكترونيات',
  'home-tools': 'أدوات منزلية',
  furniture: 'أثاث',
  doctors: 'أطباء',
  health: 'الصحة',
  teachers: 'معلمون',
  education: 'تعليم',
  jobs: 'وظائف',
  shipping: 'شحن',
  'mens-clothes': 'ملابس رجالي',
  'watches-jewelry': 'ساعات ومجوهرات',
  'free-professions': 'مهن حرة',
  'kids-toys': 'ألعاب أطفال',
  gym: 'رياضة',
  construction: 'مقاولات',
  maintenance: 'صيانة',
  'car-services': 'خدمات سيارات',
  'home-services': 'خدمات منزلية',
  'lighting-decor': 'إضاءة وديكور',
  animals: 'حيوانات',
  'farm-products': 'منتجات زراعية',
  wholesale: 'جملة',
  'production-lines': 'خطوط إنتاج',
  'light-vehicles': 'مركبات خفيفة',
  'heavy-transport': 'نقل ثقيل',
  tools: 'أدوات',
  'home-appliances': 'أجهزة منزلية',
  missing: 'مفقودات',
};

export const ALL_CATEGORIES = Object.values(CATEGORY_LABELS_AR);
